export const typeAction = {

    // auth:
    LOGIN: 'LOGIN',
    SIGNUP: 'SIGNUP',
    LOGOUT: 'LOGOUT',

    //type for product
    GET_LIST_PRODUCT: 'GET_LIST_PRODUCT',
    GET_CURRENT_PRODUCT: 'GET_CURRENT_PRODUCT',

    //type for order
    GET_LIST_ORDER: 'GET_LIST_ORDER',
    GET_CURRENT_ORDER: 'GET_CURRENT_ORDER',
    SET_CURRENT_ORDER: 'SET_CURRENT_ORDER',

    //type for admin
    GET_LIST_CUSTOMER: 'GET_LIST_CUSTOMER',
    GET_LIST_ORDER_OF_INDIVIDUAL_CUSTOMER: 'GET_LIST_ORDER_OF_INDIVIDUAL_CUSTOMER',

    //status
    ERROR: 'ERROR',
    SUCCESS: 'SUCCESS'
}