export const typeAction = {
    INC: 'inc',
    DEC: 'dec',

    //type for product
    GET_LIST_PRODUCT: 'GET_LIST_PRODUCT',
    GET_CURRENT_PRODUCT: 'GET_CURRENT_PRODUCT',

    //type for order
    GET_LIST_ORDER: 'GET_LIST_ORDER',
    GET_CURRENT_ORDER: 'GET_CURRENT_ORDER',

    //type for admin
    GET_LIST_CUSTOMER: 'GET_LIST_CUSTOMER',
    GET_LIST_ORDER_OF_INDIVIDUAL_CUSTOMER: 'GET_LIST_ORDER_OF_INDIVIDUAL_CUSTOMER',
}